In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
df=pd.read_csv("/content/qoute_dataset.csv")

In [11]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [12]:
df.shape

(3038, 2)

In [13]:
quotes=df["quote"]
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [14]:
quotes=quotes.str.lower()

In [15]:
import string
translator=str.maketrans(string.punctuation,' '*len(string.punctuation))
quotes=quotes.apply(lambda x:x.translate(translator))

In [16]:
quotes

0       “the world as we have created it is a process ...
1       “it is our choices  harry  that show what we t...
2       “there are only two ways to live your life  on...
3       “the person  be it gentleman or lady  who has ...
4       “imperfection is beauty  madness is genius and...
                              ...
3033        the past beats inside me like a second heart
3034    damn  claire  warn a guy before you do a face ...
3035    can you be a girl for a few seconds   i m alwa...
3036    that s what fiction is for  it s for getting a...
3037    if we have no peace  it is because we have for...
Name: quote, Length: 3038, dtype: object

In [17]:
from tensorflow.keras.preprocessing.text import Tokenizer
vocab_size=10000
tokenizer=Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [18]:
word_index=tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

7995

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('i', 5),
 ('a', 6),
 ('is', 7),
 ('of', 8),
 ('it', 9),
 ('that', 10)]

In [19]:
sequence=tokenizer.texts_to_sequences(quotes)
print(sequence)

[[722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74, 287, 9, 151, 12, 824, 108, 768, 74, 287, 138], [960, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14, 297, 53, 57, 74, 2510, 138], [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298, 94, 7, 6, 1062, 1, 103, 7, 35, 298, 128, 7, 6, 1062, 138], [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11, 6, 77, 1366, 121, 12, 2512, 332, 138], [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12, 691, 1178, 57, 691, 723, 138], [3722, 13, 3, 206, 6, 88, 8, 444, 281, 206, 6, 88, 8, 527, 138], [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182, 20, 23, 2, 14, 13, 138], [692, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984, 690, 10, 358, 16, 276, 138], [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9, 7, 174, 9, 17, 11, 610, 472, 138], [1063, 109, 108, 1064, 7, 42, 2, 51, 255, 138], [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3, 770, 58, 126, 9, 17, 6, 1985, 179, 18, 1, 77, 216, 7, 2, 96, 3, 473, 59, 2, 68, 133, 3, 770, 9, 58, 549, 33, 12, 15, 225, 30, 135, 508, 42, 9, 771, 18, 52, 156, 90, 136, 90, 81, 1, 282, 10, 277, 26, 2, 152, 128, 30, 68, 15, 166, 162, 225, 49, 16, 99, 81, 8, 50, 401, 156, 2514, 66, 1, 162, 225, 11, 1, 62, 35, 20, 1180, 153, 30, 135, 136, 4, 81, 89, 4, 772, 5, 266, 3, 114, 9, 120, 8, 50, 474, 412, 107, 25, 8, 50, 14, 133, 3, 402, 15, 92, 18, 2, 22, 16, 134, 58, 54, 24, 2, 134, 58, 2, 135, 48, 117, 15, 2515, 2, 135, 48, 117, 10, 333, 32, 219, 2, 249, 4, 10, 429, 20, 128, 52, 54, 2, 646, 185, 189, 16, 267, 2, 68, 1065, 646, 47, 128, 180, 268, 345, 45, 4, 73, 73, 73, 130, 11, 100, 54, 24, 2, 49, 16, 86, 32, 33, 2516, 44, 180, 15, 299, 413, 180, 15, 1370, 58, 4, 120, 1592, 180, 773, 54, 40, 17, 6, 197, 93, 4, 38, 17, 44, 107, 3, 283, 70, 138], [960, 346, 6, 157, 647, 8, 888, 3, 317, 58, 3, 74, 724, 18, 52, 35, 107, 3, 317, 58, 3, 74, 225, 138], [1066, 2, 22, 16, 889, 9, 3, 6, 890, 403, 256, 2, 49, 16, 224, 9, 100, 138], [1067, 141, 13, 12, 79, 183, 79, 263, 37, 79, 55, 69, 182, 177, 69, 141, 27, 164, 18, 24, 69, 228, 2, 148, 23, 169, 581, 69, 17, 13, 2517, 430, 16, 414, 4, 1, 204, 8, 2, 141, 48, 12, 326, 260, 18, 24, 69, 22, 66, 2, 300, 961, 2, 3, 65, 962, 4, 963, 3, 131, 194, 4, 367, 378, 345, 964, 79, 4, 134, 79, 1, 120, 2, 22, 69, 141, 13, 12, 287, 70, 2, 91, 415, 8, 1, 109, 18, 69, 33, 134, 2, 6, 216, 8, 79, 10, 69, 272, 2, 22, 2518, 92, 44, 49, 16, 278, 79, 49, 16, 165, 79, 49, 16, 1986, 4, 49, 16, 458, 53, 57, 69, 22, 134, 283, 29, 69, 219, 2, 198, 99, 79, 51, 29, 69, 219, 2, 431, 4, 582, 79, 29, 69, 17, 13, 38, 138], [692, 42, 826, 9, 1593, 58, 1, 774, 1987, 611, 7, 6, 612, 1988, 11, 235, 138], [692, 141, 13, 19, 334, 139, 5, 2519, 3, 81, 18, 5, 65, 5, 19, 1989, 58, 139, 5, 775, 3, 12, 138], [722, 827, 8, 27, 7, 13, 266, 9, 17, 776, 1, 827, 8, 489, 7, 13, 1990, 9, 17, 776, 1, 827, 8, 583, 7, 13, 2520, 9, 17, 776, 4, 1, 827, 8, 40, 7, 13, 199, 9, 17, 776, 138], [960, 7, 13, 6, 891, 8, 27, 18, 6, 891, 8, 445, 10, 219, 777, 2521, 138], [2522, 225, 77, 118, 4, 6, 2523, 892, 56, 7, 1, 1594, 40, 138], [1991, 7, 23, 335, 3, 78, 236, 21, 14, 367, 103, 1068, 138], [692, 27, 2, 108, 347, 59, 37, 29, 37, 72, 139, 5, 27, 2, 550, 108, 828, 37, 829, 5, 27, 2, 11, 56, 80, 54, 5, 36, 13, 51, 154, 103, 80, 8, 404, 18, 56, 11, 122, 38, 7, 46, 5, 37, 2, 44, 1371, 10, 15, 308, 250, 28, 725, 7, 28, 308, 44, 1371, 10, 29, 5, 229, 648, 15, 220, 405, 138], [3723, 91, 649, 2, 14, 778, 2, 243, 1992, 1372, 8, 205, 138], [1066, 2, 726, 43, 2, 19, 46, 67, 3, 27, 50, 138], [2524, 32, 584, 965, 11, 1595, 22, 66, 2, 6, 1596, 121, 401, 65, 10, 965, 11, 6, 1993, 22, 66, 2, 6, 830, 138], [3724, 7, 11, 1, 650, 8, 1, 1597, 4, 9, 141, 12, 612, 72, 67, 3, 67, 3, 134, 6, 332, 37, 1994, 1597, 6, 475, 650, 138], [3725, 2, 14, 2, 10, 7, 1995, 57, 166, 38, 7, 46, 39, 385, 32, 7, 2525, 57, 2, 138], [1066, 2, 60, 15, 318, 3, 12, 585, 124, 50, 651, 613, 24, 2, 60, 50, 3, 12, 53, 585, 124, 50, 53, 651, 613, 138], [960, 7, 386, 3, 82, 108, 1598, 47, 83, 476, 2, 82, 44, 2526, 10, 2, 257, 35, 153, 13, 19, 432, 47, 25, 11, 122, 831, 2, 646, 64, 1996, 138], [3726, 33, 96, 2, 72, 6, 3, 1599, 490, 33, 96, 2, 1373, 138], [3727, 77, 93, 70, 309, 29, 9, 1181, 2, 2, 132, 46, 210, 138], [722, 53, 10, 2, 124, 1, 53, 63, 2, 33, 51, 1, 53, 10, 2, 211, 1, 53, 586, 2, 135, 81, 138], [3728, 477, 9, 7, 966, 217, 15, 299, 377, 18, 160, 45, 269, 127, 10, 267, 10, 9, 7, 13, 214, 138], [722, 179, 7, 238, 7, 133, 3, 278, 2, 2, 52, 212, 3, 117, 1, 282, 336, 416, 20, 138], [2527, 25, 8, 78, 22, 36, 157, 63, 18, 21, 22, 36, 301, 63, 26, 157, 27, 138], [1600, 1, 153, 2528, 170, 199, 7, 18, 1, 387, 157, 727, 138], [3729, 2, 172, 7, 27, 18, 6, 142, 1374, 148, 4, 86, 189, 16, 278, 138], [2529, 124, 3, 51, 21, 68, 13, 213, 138], [3730, 528, 22, 51, 1, 348, 7, 3, 224, 138], [692, 19, 73, 1601, 10, 1602, 33, 12, 6, 201, 8, 551, 138], [960, 7, 48, 89, 587, 3, 12, 23, 2, 257, 19, 123, 138], [1063, 832, 226, 6, 446, 226, 177, 31, 652, 71, 2530, 1, 88, 32, 48, 779, 226, 55, 39, 138], [1067, 22, 48, 96, 6, 833, 8, 825, 653, 155, 37, 6, 137, 175, 155, 3, 1375, 34, 138], [1067, 130, 359, 44, 2, 1069, 211, 3, 284, 46, 39, 18, 100, 138], [1066, 2, 22, 66, 6, 178, 300, 2, 22, 66, 79, 36, 158, 138], [1991, 7, 42, 2531, 6, 1997, 3, 180, 15, 1603, 2, 121, 180, 693, 138], [722, 214, 893, 7, 1, 88, 32, 22, 2532, 2, 64, 967, 15, 1998, 37, 773, 111, 15, 220, 37, 52, 968, 111, 654, 138], [1063, 491, 195, 1604, 18, 189, 16, 27, 1376, 18, 189, 16, 130, 4, 614, 177, 69, 7, 349, 138], [3731, 11, 1, 433, 22, 2, 87, 1, 258, 138], [960, 581, 13, 23, 105, 7, 492, 18, 23, 30, 288, 3, 12, 138], [3732, 150, 13, 478, 4, 192, 1, 80, 21, 493, 3, 65, 9, 150, 27, 7, 6, 1070, 27, 7, 6, 459, 27, 7, 6, 1182, 58, 138], [1365, 7, 94, 5, 98, 13, 36, 20, 101, 32, 14, 129, 28, 225, 5, 19, 46, 1605, 8, 404, 43, 64, 1999, 9, 7, 13, 28, 615, 138], [2533, 39, 93, 91, 109, 10, 1606, 2, 138], [692, 85, 77, 18, 13, 76, 694, 5, 36, 728, 18, 5, 85, 13, 1, 1377, 5, 85, 52, 6, 301, 195, 11, 6, 509, 62, 268, 3, 117, 105, 3, 27, 138], [1066, 5, 116, 13, 6, 2534, 5, 98, 655, 12, 6, 2535, 5, 273, 65, 11, 309, 5, 82, 28, 2536, 11, 309, 5, 87, 28, 40, 11, 1378, 8, 309, 138], [1066, 2, 55, 124, 1, 118, 10, 238, 169, 7, 230, 2, 22, 55, 65, 23, 238, 169, 7, 287, 138], [722, 494, 251, 645, 4, 1071, 7, 645, 84, 146, 2000, 138], [3733, 17, 42, 6, 1607, 20, 2, 1608, 138], [1365, 7, 46, 207, 35, 1379, 35, 6, 137, 138], [3734, 39, 310, 8, 205, 2537, 159, 1183, 18, 273, 21, 161, 44, 175, 47, 1, 1184, 310, 10, 21, 36, 13, 87, 1, 39, 122, 84, 123, 969, 20, 78, 138], [1991, 264, 16, 70, 1185, 100, 40, 7, 70, 1072, 100, 138], [3735, 17, 1, 780, 26, 2538, 5, 221, 35, 5, 2539, 202, 6, 616, 24, 83, 239, 335, 2, 616, 11, 76, 834, 3, 244, 24, 83, 77, 335, 2, 616, 11, 781, 3, 2540, 4, 24, 94, 335, 2, 616, 3, 66, 83, 337, 138], [1067, 196, 244, 1, 231, 8, 1, 104, 32, 41, 15, 263, 208, 138], [2541, 21, 68, 2001, 11, 27, 44, 9, 17, 25, 119, 3, 529, 34, 2542, 2, 132, 42, 9, 138], [1600, 27, 47, 25, 7, 3, 12, 970, 27, 158, 4, 15, 92, 33, 12, 2543, 4, 894, 327, 24, 2, 60, 3, 66, 302, 8, 1186, 9, 1609, 2, 121, 134, 9, 3, 46, 39, 13, 110, 76, 1073, 1187, 9, 1610, 1074, 26, 2544, 4, 142, 2545, 617, 25, 2546, 1611, 9, 58, 782, 11, 1, 1612, 37, 2547, 8, 15, 2002, 18, 11, 10, 1612, 782, 338, 2548, 2549, 9, 33, 165, 9, 33, 13, 12, 327, 9, 33, 206, 1613, 2550, 2551, 3, 27, 7, 3, 12, 970, 138], [2527, 25, 101, 32, 1614, 14, 350, 138], [2533, 13, 1188, 1, 460, 377, 1188, 1, 235, 4, 618, 25, 101, 32, 82, 108, 27, 138], [1365, 7, 94, 3, 552, 25, 2, 36, 7, 351, 163, 47, 6, 2552, 4, 1189, 138], [3736, 176, 109, 4, 12, 328, 26, 9, 2, 19, 328, 23, 2, 112, 90, 2553, 4, 2003, 46, 695, 2554, 11, 244, 50, 35, 696, 35, 2, 22, 417, 7, 6, 232, 109, 2, 245, 478, 9, 2555, 4, 26, 89, 413, 6, 729, 3, 12, 2556, 26, 15, 256, 826, 138], [692, 19, 48, 99, 28, 2557, 2558, 26, 28, 697, 138], [692, 19, 619, 38, 14, 730, 8, 53, 57, 39, 201, 90, 136, 72, 835, 4, 90, 136, 72, 368, 18, 5, 102, 2004, 6, 509, 2559, 5, 95, 25, 698, 2, 87, 148, 28, 730, 14, 133, 3, 19, 730, 26, 34, 138], [1066, 5, 113, 6, 731, 20, 91, 67, 5, 221, 8, 2, 5, 112, 289, 152, 28, 1190, 227, 138], [2560, 43, 48, 81, 447, 23, 471, 895, 226, 30, 121, 896, 138], [722, 732, 26, 311, 76, 360, 170, 8, 477, 7, 10, 43, 33, 1380, 45, 656, 620, 4, 268, 3, 279, 63, 11, 9, 138], [3737, 349, 4, 65, 119, 4, 65, 1075, 4, 65, 413, 479, 1, 584, 2, 22, 65, 58, 24, 55, 2, 261, 138], [3738, 129, 2561, 34, 75, 7, 6, 137, 10, 29, 2, 68, 25, 328, 230, 9, 2, 329, 1, 1381, 10, 588, 9, 41, 6, 1615, 207, 8, 434, 4, 2, 112, 418, 97, 58, 45, 1, 1616, 733, 2, 274, 42, 9, 10, 189, 16, 337, 107, 298, 138], [722, 330, 5, 339, 3, 202, 7, 54, 319, 1, 55, 39, 836, 971, 5, 621, 138], [1067, 141, 114, 5, 95, 6, 1191, 18, 5, 95, 13, 1, 55, 39, 5, 208, 783, 2, 135, 1617, 78, 4, 1, 62, 33, 82, 35, 39, 138], [692, 85, 448, 8, 25, 1192, 5, 266, 238, 1382, 138], [722, 495, 264, 16, 32, 7, 133, 3, 99, 34, 9, 17, 32, 7, 133, 3, 252, 34, 138], [3739, 6, 137, 122, 43, 2005, 4, 49, 16, 124, 138], [2524, 32, 84, 48, 209, 6, 784, 84, 48, 657, 158, 232, 138], [1063, 887, 17, 490, 7, 184, 2562, 9, 2006, 72, 2563, 3, 27, 72, 27, 3, 2564, 11, 6, 186, 138], [2541, 24, 1, 67, 127, 136, 29, 2, 19, 3, 66, 6, 435, 251, 23, 7, 119, 4, 23, 7, 388, 156, 23, 406, 3, 6, 496, 32, 41, 77, 4, 201, 4, 589, 54, 31, 2565, 734, 1, 785, 8, 735, 2007, 156, 2566, 2567, 138], [692, 1618, 222, 25, 38, 7, 46, 2568, 42, 230, 59, 107, 1383, 39, 2008, 8, 154, 93, 57, 8, 6, 137, 29, 5, 19, 6, 449, 8, 28, 125, 5, 245, 12, 1193, 24, 5, 19, 13, 76, 2009, 551, 138], [1365, 14, 369, 43, 590, 5, 129, 27, 4, 171, 2569, 8, 590, 5, 65, 153, 1, 53, 5, 87, 8, 1, 62, 1, 53, 85, 5, 2570, 26, 9, 4, 91, 109, 2571, 28, 837, 8, 1, 2572, 8, 25, 194, 838, 4, 8, 1, 142, 2573, 10, 22, 12, 2574, 45, 1, 2575, 8, 2010, 37, 497, 138], [2560, 109, 2, 33, 12, 256, 155, 3, 352, 230, 651, 613, 164, 138], [2529, 14, 13, 1194, 2011, 10, 147, 33, 36, 1, 162, 20, 78, 21, 14, 1384, 59, 658, 1, 162, 33, 480, 75, 3, 12, 138], [722, 193, 8, 199, 2576, 72, 1, 193, 8, 40, 6, 88, 32, 226, 897, 7, 1619, 3, 187, 47, 154, 67, 138], [1063, 361, 22, 591, 333, 80, 200, 1, 62, 236, 1, 179, 7, 1620, 45, 146, 1076, 138], [692, 130, 11, 2012, 35, 5, 130, 10, 1, 461, 84, 2013, 13, 55, 54, 5, 87, 9, 18, 54, 64, 9, 5, 87, 128, 169, 138], [722, 179, 699, 1621, 9, 7, 6, 197, 4, 700, 93, 4, 127, 659, 12, 2014, 26, 157, 1622, 138], [692, 95, 1, 39, 10, 17, 212, 3, 187, 29, 9, 17, 67, 20, 34, 3, 187, 44, 99, 34, 82, 28, 40, 1, 80, 5, 60, 3, 138], [1600, 187, 33, 12, 76, 1385, 509, 727, 138], [960, 346, 270, 3, 288, 58, 4, 206, 32, 2, 129, 14, 138], [3740, 149, 3, 96, 278, 64, 1, 179, 57, 2577, 26, 6, 361, 138], [1067, 48, 129, 224, 6, 104, 174, 2, 1195, 63, 72, 61, 348, 8, 1077, 174, 2, 1623, 217, 8, 61, 660, 4, 289, 200, 11, 9, 138], [1067, 19, 3, 253, 1, 137, 10, 370, 3, 12, 592, 4, 24, 1, 137, 33, 12, 89, 786, 20, 1078, 1079, 86, 2, 253, 9, 20, 318, 138], [2578, 140, 1, 179, 3, 43, 32, 14, 13, 1080, 8, 9, 138], [1063, 104, 17, 6, 104, 46, 191, 59, 301, 138], [3741, 6, 170, 553, 118, 35, 6, 1386, 553, 6, 2579, 24, 9, 7, 3, 180, 146, 972, 138], [12, 100, 238, 169, 7, 389, 736], [5, 95, 1624, 2580, 4, 6, 142, 2015, 5, 66, 378, 5, 85, 75, 8, 510, 4, 47, 280, 246, 3, 2016, 18, 24, 2, 22, 16, 2016, 34, 47, 28, 701, 86, 2, 302, 35, 303, 49, 16, 554, 34, 47, 28, 162], [44, 167, 118, 44, 142, 67], [204, 63, 14, 622, 1, 320, 4, 194, 1071, 4, 5, 95, 13, 302, 70, 1, 320], [6, 462, 108, 118, 7, 42, 6, 436, 108, 6, 168], [12, 32, 2, 14, 4, 114, 23, 2, 132, 54, 101, 32, 170, 49, 16, 191, 4, 101, 32, 191, 49, 16, 170], [2, 102, 1387, 555, 42, 38, 17, 407, 1081, 27, 42, 2, 135, 48, 12, 278, 702, 42, 38, 17, 407, 898, 4, 82, 42, 9, 17, 623, 45, 269], [2, 51, 2, 68, 11, 27, 29, 2, 22, 16, 229, 648, 54, 312, 7, 530, 149, 57, 15, 247], [2, 55, 82, 185, 18, 24, 2, 36, 9, 119, 185, 7, 155], [12, 1, 165, 10, 2, 329, 3, 87, 11, 1, 62], [11, 379, 145, 5, 22, 2581, 58, 128, 5, 102, 511, 70, 40, 9, 429, 45], [24, 2, 60, 3, 51, 23, 6, 88, 17, 42, 203, 6, 77, 161, 47, 59, 31, 1388, 61, 3742, 13, 61, 2582], [196, 289, 11, 556, 8, 2017, 5, 141, 13, 3743, 289, 368, 2017, 5, 141, 13, 3744, 1196, 2017, 52, 12, 28, 207], [24, 2, 140, 1, 179, 2, 49, 16, 19, 3, 156, 158], [445, 7, 492, 47, 1, 186, 29, 39, 88, 290, 3, 159, 23, 2, 89, 5, 221, 10, 46, 39, 18, 202], [5, 102, 511, 10, 43, 33, 244, 23, 2, 71, 43, 33, 244, 23, 2, 173, 18, 43, 33, 48, 244, 59, 2, 209, 50, 132], [6, 207, 7, 105, 32, 272, 25, 70, 2, 4, 171, 228, 2], [3, 82, 7, 1, 1389, 93, 11, 1, 62, 120, 43, 390, 10, 7, 25], [73, 437, 15, 724, 94, 2583, 50, 44, 107], [433, 151, 839, 75, 433, 55, 233, 22, 36, 10, 266, 151, 839, 75, 266, 55, 27, 22, 36, 10], [82, 35, 24, 2, 116, 3, 187, 417, 211, 35, 24, 2, 116, 3, 82, 227], [21, 621, 1, 27, 21, 65, 21, 554], [108, 309, 40, 98, 12, 6, 784], [5, 85, 44, 2018, 10, 126, 5, 49, 16, 224, 6, 512, 340, 8, 23, 5, 85, 291], [3, 12, 100, 11, 6, 62, 10, 7, 899, 268, 3, 66, 2, 83, 169, 7, 1, 557, 3745], [215, 17, 3, 1, 447, 282, 1, 3746, 1, 3747, 1, 3748, 1, 1074, 3749, 11, 1, 2584, 2019, 1, 282, 32, 87, 63, 973, 30, 68, 13, 1390, 8, 840, 4, 30, 19, 46, 419, 20, 1, 3750, 3751, 2, 22, 1625, 50, 2020, 26, 50, 3752, 37, 3753, 50, 70, 1, 55, 93, 2, 22, 16, 36, 7, 974, 50, 54, 30, 165, 63, 30, 1626, 1, 194, 2021, 661, 4, 236, 90, 141, 87, 50, 35, 1, 447, 282, 21, 87, 645, 54, 1, 43, 32, 14, 447, 155, 3, 65, 30, 22, 165, 1, 62, 14, 1, 282, 32, 36], [1197, 7, 271, 1, 218, 93, 144, 4, 144, 164, 18, 1627, 380, 2022], [5, 130, 10, 128, 335, 20, 6, 330, 43, 165, 44, 10, 2, 22, 211, 3, 99, 81, 63, 81, 223, 44, 10, 2, 1391, 50, 29, 30, 68, 119, 2, 130, 359, 44, 2, 1069, 211, 3, 284, 46, 39, 18, 100, 4, 126, 77, 63, 229, 513, 44, 149, 63, 22, 229, 260], [9, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182, 20, 23, 2, 14, 13], [1392, 234, 72, 148, 2, 33, 12, 53, 1082, 64, 1, 63, 10, 2, 321, 16, 36, 57, 64, 1, 282, 2, 173, 36, 44, 624, 248, 1, 3754, 2585, 240, 72, 1, 782, 2023, 1083, 1, 1393, 1628, 11, 15, 2586, 1394, 237, 787], [55, 185, 11, 15, 40, 5, 471, 130, 2, 117, 105, 32, 22, 514, 480, 15, 62, 200, 2, 140, 50, 63, 10, 662, 48, 1629, 26, 159, 168, 4, 30, 2024, 128, 2, 114, 4, 474, 60, 3, 371, 53, 2, 737, 1395, 20, 1, 241, 247, 10, 33, 48, 136, 166, 2587, 10, 116, 48, 1396, 4, 1, 167, 3755, 40, 84, 2025, 47, 2, 29, 83, 703, 335, 2, 558, 391, 3, 140, 50, 70, 9, 347, 30, 33, 737, 11, 15, 2026, 30, 14, 13, 2588, 3, 593, 26, 2, 29, 2, 14, 2589, 37, 300, 26, 2, 29, 2, 66, 6, 528, 8, 100, 48, 36, 30, 278, 15, 594, 37, 66, 2, 132, 42, 2, 14, 13, 77, 155, 18, 281, 30, 663, 2, 58, 4, 427, 2, 1, 63, 70, 100, 10, 66, 2, 531, 4, 110, 197, 38, 7, 48, 154, 2590, 2027, 37, 3756, 18, 55, 6, 975, 3757, 29, 30, 14, 200, 2, 22, 12, 100, 4, 13, 704, 70, 23, 30, 33, 65, 8, 2, 54, 30, 27, 2, 20, 32, 2, 14, 1, 63, 10, 493, 2591, 3, 120, 43, 392, 35, 6, 1198, 664, 37, 289, 206, 3758, 2028, 900, 782, 11, 15, 92, 3, 2029, 227, 532, 8, 15, 976, 136, 143, 4, 14, 44, 977, 4, 3759, 313, 42, 131, 438, 164, 2592, 493, 3760, 4, 53, 1397, 665, 463, 216, 8, 1630, 40, 139, 177, 9, 41, 3761, 37, 666, 390, 47, 25, 6, 1616, 418, 37, 204, 1398, 1, 109, 2030, 3, 96, 2, 152, 6, 175, 3762, 276, 4, 73, 978, 6, 283, 3, 15, 231, 11, 106, 1399, 1084, 46, 172, 20, 3763, 2031, 18, 2, 117, 353, 515, 1199, 11, 52, 311, 50, 2593, 63, 10, 48, 2594, 2, 177, 206, 2032, 54, 2, 51, 30, 14, 304, 3, 56, 104, 32, 7, 44, 531, 3, 2, 2, 65, 8, 56, 104, 45, 91, 3764, 4, 11, 128, 2, 36, 420, 63, 667, 50, 3, 170, 42, 6, 1200, 738, 559, 1201, 668, 37, 110, 6, 560, 1631, 45, 1, 1632, 2, 360, 15, 92, 347, 10, 1084, 6, 841, 9, 141, 12, 327, 39, 109, 4, 11, 1633, 15, 92, 2, 354, 6, 27, 4, 533, 10, 2, 48, 1202, 393, 2, 117, 10, 131, 970, 7, 1, 55, 80, 3, 901, 15, 92, 3, 132, 166, 609, 705, 44, 214, 9, 1606, 2, 2, 117, 394, 11, 347, 2, 19, 6, 166, 207, 4, 894, 6, 168, 979, 32, 33, 669, 1379, 3, 1, 192, 40, 463, 514, 380, 2595, 4, 1400, 15, 55, 208, 4, 2033, 7, 11, 347, 10, 30, 14, 6, 216, 8, 15, 40], [25, 10, 7, 902, 150, 13, 3765, 13, 25, 101, 32, 1614, 14, 350, 1, 256, 10, 7, 325, 150, 13, 3766, 372, 1203, 14, 13, 2034, 64, 1, 3767, 72, 1, 2035, 6, 285, 245, 12, 3768, 6, 233, 72, 1, 1204, 245, 788, 2596, 245, 12, 2597, 10, 41, 327, 1, 3769, 164, 245, 12, 1634], [1, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11, 6, 77, 1366, 121, 12, 2512, 332], [9, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14, 297, 53, 57, 74, 2510], [3770, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12, 691, 1178, 57, 691, 723], [38, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298, 94, 7, 6, 1062, 1, 103, 7, 35, 298, 128, 7, 6, 1062], [9, 150, 13, 36, 3, 1635, 45, 247, 4, 244, 3, 82], [77, 225, 77, 118, 4, 6, 2523, 892, 56, 7, 1, 1594, 40], [35, 31, 124, 5, 789, 11, 27, 1, 80, 2, 229, 648, 1401, 4, 86, 25, 47, 185], [21, 14, 25, 11, 1, 3771, 18, 90, 8, 78, 14, 259, 47, 1, 258], [651, 613, 14, 53, 57, 166, 13, 54, 30, 140, 78, 10, 842, 390, 18, 54, 30, 140, 78, 10, 842, 22, 12, 3772], [1, 528, 2036, 65, 31, 7, 491, 18, 1, 491, 88, 272, 341, 3, 12, 6, 528], [9, 7, 149, 3, 669, 706, 47, 1, 843, 8, 131, 221, 6, 528, 57, 3, 339, 4, 2598, 25, 695, 8, 9], [733, 2, 117, 100, 45, 1, 381, 8, 1, 1636, 9, 7, 67, 3, 3773, 37, 2599, 4, 2600], [40, 7, 23, 335, 3, 78, 236, 21, 14, 367, 103, 1068], [903, 7, 450, 417, 7, 6, 1085, 451, 7, 6, 844, 8, 147, 122, 7, 160, 21, 418, 9, 1, 670], [5, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984, 690, 10, 358, 16, 276], [9, 7, 13, 6, 891, 8, 27, 18, 6, 891, 8, 445, 10, 219, 777, 2521], [1, 827, 8, 27, 7, 13, 266, 9, 17, 776, 1, 827, 8, 489, 7, 13, 1990, 9, 17, 776, 1, 827, 8, 583, 7, 13, 2520, 9, 17, 776, 4, 1, 827, 8, 40, 7, 13, 199, 9, 17, 776], [1, 88, 32, 150, 13, 124, 84, 46, 2601, 144, 1, 88, 32, 151, 124], [6, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9, 7, 174, 9, 17, 11, 610, 472], [5, 27, 2, 108, 347, 59, 37, 29, 37, 72, 139, 5, 27, 2, 550, 108, 828, 37, 829, 5, 27, 2, 11, 56, 80, 54, 5, 36, 13, 51, 154, 103, 80, 8, 404, 18, 56, 11, 122, 38, 7, 46, 5, 37, 2, 44, 1371, 10, 15, 308, 250, 28, 725, 7, 28, 308, 44, 1371, 10, 29, 5, 229, 648, 15, 220, 405], [5, 141, 13, 19, 334, 139, 5, 2519, 3, 81, 18, 5, 65, 5, 19, 1989, 58, 139, 5, 775, 3, 12], [24, 2, 49, 16, 317, 20, 83, 2, 33, 229, 20, 158], [739, 8, 6, 1086, 6, 137, 7, 88, 17, 162, 207, 217, 8, 6, 1086, 9, 17, 89, 338, 3, 124], [5, 3774, 1087, 10, 5, 85, 58, 3, 46, 77], [5, 85, 155, 8, 76, 1205, 3, 2037, 2602, 250, 28, 490, 490, 7, 53, 304, 57, 516, 516, 7, 1402, 490, 3775, 1, 62], [27, 25, 284, 6, 369, 36, 223, 3, 625, 12, 452, 20, 2603, 3776, 11, 362, 57, 395, 4, 180, 1088, 3777, 1088, 125, 40, 17, 1206, 12, 2604, 181, 20, 396, 18, 48, 3778, 181, 20, 2605], [19, 2, 115, 123, 11, 27, 895, 264, 16, 9, 9, 219, 2, 44, 970, 9, 1183, 15, 725, 4, 9, 1183, 58, 15, 92, 4, 9, 292, 10, 105, 22, 96, 217, 2, 4, 770, 2, 58], [5, 42, 826, 9, 1593, 58, 1, 774, 1987, 611, 7, 6, 612, 1988, 11, 235], [6, 832, 226, 6, 446, 226, 177, 31, 652, 71, 2530, 1, 88, 32, 48, 779, 226, 55, 39], [6, 109, 108, 1064, 7, 42, 2, 51, 255], [48, 279, 248, 904, 417, 23, 141, 12, 328, 109, 222, 417, 52, 35, 153], [131, 845, 182, 64, 105, 517, 2, 394, 236, 404, 105, 845, 517, 2, 270], [2, 19, 2606, 11, 15, 299, 2, 19, 534, 11, 15, 1076, 2, 22, 3779, 100, 154, 1089, 2, 373, 2, 68, 45, 15, 125, 4, 2, 51, 23, 2, 51, 4, 2, 14, 1, 39, 32, 135, 473, 139, 3, 81], [10, 122, 150, 13, 439, 78, 219, 78, 535], [9, 7, 48, 89, 587, 3, 12, 23, 2, 257, 19, 123], [20, 91, 649, 2, 14, 778, 2, 243, 1992, 1372, 8, 205], [56, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3, 770, 58, 126, 9, 17, 6, 1985, 179, 18, 1, 77, 216, 7, 2, 96, 3, 473, 59, 2, 68, 133, 3, 770, 9, 58, 549, 33, 12, 15, 225, 30, 135, 508, 42, 9, 771, 18, 52, 156, 90, 136, 90, 81, 1, 282, 10, 277, 26, 2, 152, 128, 30, 68, 15, 166, 162, 225, 49, 16, 99, 81, 8, 50, 401, 156, 2514, 66, 1, 162, 225, 11, 1, 62, 35, 20, 1180, 153, 30, 135, 136, 4, 81, 89, 4, 772, 5, 266, 3, 114, 9, 120, 8, 50, 474, 412, 107, 25, 8, 50, 14, 133, 3, 402, 15, 92, 18, 2, 22, 16, 134, 58, 54, 24, 2, 134, 58, 2, 135, 48, 117, 15, 2515, 2, 135, 48, 117, 10, 333, 32, 219, 2, 249, 4, 10, 429, 20, 128, 52,

In [20]:
X=[]
y=[]
for seq in sequence:
  for i in range(1,len(seq)):
    input_seq=seq[:i]
    output_seq=seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [21]:
X

[[722],
 [722, 62],
 [722, 62, 35],
 [722, 62, 35, 21],
 [722, 62, 35, 21, 19],
 [722, 62, 35, 21, 19, 885],
 [722, 62, 35, 21, 19, 885, 9],
 [722, 62, 35, 21, 19, 885, 9, 7],
 [722, 62, 35, 21, 19, 885, 9, 7, 6],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74, 287],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74, 287, 9],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74, 287, 9, 151],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74, 287, 9, 151, 12],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74, 287, 9, 151, 12, 824],
 [722, 62, 35, 21, 19, 885, 9, 7, 6, 1177, 8, 74, 287, 9, 151, 12, 824, 108],
 [722,
  62,
  35,
  21,
  19,
  885,
  9,
  7,
  6,
  1177,
  8,
  74,
  287,
  9,
  151,
  12,
  824,
  108,
  768],
 [722,
  62,
  35,
  21,
  19,
  885,
  9,
  7,
  6,
  1177,
  8,
  74,
  287,
  9,
  151,
  12,
  824,
  108,
  768,
  74],
 [722,
  62,
  35,
  21,
  19,
  885,
  9,
  7,
  6,
  1177,
  8,
  74,
  287,
  9,
  151,
  12,
  824,
  108,
  768,
  74,
  287],
 [960],
 [960, 7],
 [960, 7, 74],
 [960, 7, 74, 886],
 [960, 7, 74, 886, 377],
 [960, 7, 74, 886, 377, 10],
 [960, 7, 74, 886, 377, 10, 427],
 [960, 7, 74, 886, 377, 10, 427, 23],
 [960, 7, 74, 886, 377, 10, 427, 23, 21],
 [960, 7, 74, 886, 377, 10, 427, 23, 21, 471],
 [960, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14],
 [960, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14, 297],
 [960, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14, 297, 53],
 [960, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14, 297, 53, 57],
 [960, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14, 297, 53, 57, 74],
 [960, 7, 74, 886, 377, 10, 427, 23, 21, 471, 14, 297, 53, 57, 74, 2510],
 [1365],
 [1365, 14],
 [1365, 14, 55],
 [1365, 14, 55, 204],
 [1365, 14, 55, 204, 690],
 [1365, 14, 55, 204, 690, 3],
 [1365, 14, 55, 204, 690, 3, 82],
 [1365, 14, 55, 204, 690, 3, 82, 15],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298, 94],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298, 94, 7],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298, 94, 7, 6],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298, 94, 7, 6, 1062],
 [1365, 14, 55, 204, 690, 3, 82, 15, 40, 39, 7, 35, 298, 94, 7, 6, 1062, 1],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103,
  7],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103,
  7,
  35],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103,
  7,
  35,
  298],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103,
  7,
  35,
  298,
  128],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103,
  7,
  35,
  298,
  128,
  7],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103,
  7,
  35,
  298,
  128,
  7,
  6],
 [1365,
  14,
  55,
  204,
  690,
  3,
  82,
  15,
  40,
  39,
  7,
  35,
  298,
  94,
  7,
  6,
  1062,
  1,
  103,
  7,
  35,
  298,
  128,
  7,
  6,
  1062],
 [722],
 [722, 104],
 [722, 104, 12],
 [722, 104, 12, 9],
 [722, 104, 12, 9, 2511],
 [722, 104, 12, 9, 2511, 37],
 [722, 104, 12, 9, 2511, 37, 887],
 [722, 104, 12, 9, 2511, 37, 887, 32],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11, 6],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11, 6, 77],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11, 6, 77, 1366],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11, 6, 77, 1366, 121],
 [722, 104, 12, 9, 2511, 37, 887, 32, 84, 13, 609, 11, 6, 77, 1366, 121, 12],
 [722,
  104,
  12,
  9,
  2511,
  37,
  887,
  32,
  84,
  13,
  609,
  11,
  6,
  77,
  1366,
  121,
  12,
  2512],
 [722,
  104,
  12,
  9,
  2511,
  37,
  887,
  32,
  84,
  13,
  609,
  11,
  6,
  77,
  1366,
  121,
  12,
  2512,
  332],
 [3721],
 [3721, 7],
 [3721, 7, 316],
 [3721, 7, 316, 769],
 [3721, 7, 316, 769, 7],
 [3721, 7, 316, 769, 7, 645],
 [3721, 7, 316, 769, 7, 645, 4],
 [3721, 7, 316, 769, 7, 645, 4, 9],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12, 691],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12, 691, 1178],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12, 691, 1178, 57],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12, 691, 1178, 57, 691],
 [3721, 7, 316, 769, 7, 645, 4, 9, 17, 149, 3, 12, 691, 1178, 57, 691, 723],
 [3722],
 [3722, 13],
 [3722, 13, 3],
 [3722, 13, 3, 206],
 [3722, 13, 3, 206, 6],
 [3722, 13, 3, 206, 6, 88],
 [3722, 13, 3, 206, 6, 88, 8],
 [3722, 13, 3, 206, 6, 88, 8, 444],
 [3722, 13, 3, 206, 6, 88, 8, 444, 281],
 [3722, 13, 3, 206, 6, 88, 8, 444, 281, 206],
 [3722, 13, 3, 206, 6, 88, 8, 444, 281, 206, 6],
 [3722, 13, 3, 206, 6, 88, 8, 444, 281, 206, 6, 88],
 [3722, 13, 3, 206, 6, 88, 8, 444, 281, 206, 6, 88, 8],
 [3722, 13, 3, 206, 6, 88, 8, 444, 281, 206, 6, 88, 8, 527],
 [960],
 [960, 7],
 [960, 7, 149],
 [960, 7, 149, 3],
 [960, 7, 149, 3, 12],
 [960, 7, 149, 3, 12, 1367],
 [960, 7, 149, 3, 12, 1367, 20],
 [960, 7, 149, 3, 12, 1367, 20, 23],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182, 20],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182, 20, 23],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182, 20, 23, 2],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182, 20, 23, 2, 14],
 [960, 7, 149, 3, 12, 1367, 20, 23, 2, 14, 57, 3, 12, 182, 20, 23, 2, 14, 13],
 [692],
 [692, 19],
 [692, 19, 13],
 [692, 19, 13, 1368],
 [692, 19, 13, 1368, 5],
 [692, 19, 13, 1368, 5, 102],
 [692, 19, 13, 1368, 5, 102, 52],
 [692, 19, 13, 1368, 5, 102, 52, 428],
 [692, 19, 13, 1368, 5, 102, 52, 428, 1179],
 [692, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984],
 [692, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984, 690],
 [692, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984, 690, 10],
 [692, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984, 690, 10, 358],
 [692, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984, 690, 10, 358, 16],
 [692, 19, 13, 1368, 5, 102, 52, 428, 1179, 1984, 690, 10, 358, 16, 276],
 [1063],
 [1063, 178],
 [1063, 178, 7],
 [1063, 178, 7, 42],
 [1063, 178, 7, 42, 6],
 [1063, 178, 7, 42, 6, 825],
 [1063, 178, 7, 42, 6, 825, 1369],
 [1063, 178, 7, 42, 6, 825, 1369, 2],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9, 7],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9, 7, 174],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9, 7, 174, 9],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9, 7, 174, 9, 17],
 [1063, 178, 7, 42, 6, 825, 1369, 2, 48, 51, 59, 325, 9, 7, 174, 9, 17, 11],
 [1063,
  178,
  7,
  42,
  6,
  825,
  1369,
  2,
  48,
  51,
  59,
  325,
  9,
  7,
  174,
  9,
  17,
  11,
  610],
 [1063,
  178,
  7,
  42,
  6,
  825,
  1369,
  2,
  48,
  51,
  59,
  325,
  9,
  7,
  174,
  9,
  17,
  11,
  610,
  472],
 [1063],
 [1063, 109],
 [1063, 109, 108],
 [1063, 109, 108, 1064],
 [1063, 109, 108, 1064, 7],
 [1063, 109, 108, 1064, 7, 42],
 [1063, 109, 108, 1064, 7, 42, 2],
 [1063, 109, 108, 1064, 7, 42, 2, 51],
 [1063, 109, 108, 1064, 7, 42, 2, 51, 255],
 [2513],
 [2513, 40],
 [2513, 40, 7],
 [2513, 40, 7, 23],
 [2513, 40, 7, 23, 2],
 [2513, 40, 7, 23, 2, 66],
 [2513, 40, 7, 23, 2, 66, 9],
 [2513, 40, 7, 23, 2, 66, 9, 46],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3, 770],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3, 770, 58],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3, 770, 58, 126],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3, 770, 58, 126, 9],
 [2513, 40, 7, 23, 2, 66, 9, 46, 191, 23, 2, 68, 133, 3, 770, 58, 126, 9, 17],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,
  136],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,
  136,
  90],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,
  136,
  90,
  81],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,
  136,
  90,
  81,
  1],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,
  136,
  90,
  81,
  1,
  282],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,
  136,
  90,
  81,
  1,
  282,
  10],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,
  136,
  90,
  81,
  1,
  282,
  10,
  277],
 [2513,
  40,
  7,
  23,
  2,
  66,
  9,
  46,
  191,
  23,
  2,
  68,
  133,
  3,
  770,
  58,
  126,
  9,
  17,
  6,
  1985,
  179,
  18,
  1,
  77,
  216,
  7,
  2,
  96,
  3,
  473,
  59,
  2,
  68,
  133,
  3,
  770,
  9,
  58,
  549,
  33,
  12,
  15,
  225,
  30,
  135,
  508,
  42,
  9,
  771,
  18,
  52,
  156,
  90,

In [22]:
y

[62,
 35,
 21,
 19,
 885,
 9,
 7,
 6,
 1177,
 8,
 74,
 287,
 9,
 151,
 12,
 824,
 108,
 768,
 74,
 287,
 138,
 7,
 74,
 886,
 377,
 10,
 427,
 23,
 21,
 471,
 14,
 297,
 53,
 57,
 74,
 2510,
 138,
 14,
 55,
 204,
 690,
 3,
 82,
 15,
 40,
 39,
 7,
 35,
 298,
 94,
 7,
 6,
 1062,
 1,
 103,
 7,
 35,
 298,
 128,
 7,
 6,
 1062,
 138,
 104,
 12,
 9,
 2511,
 37,
 887,
 32,
 84,
 13,
 609,
 11,
 6,
 77,
 1366,
 121,
 12,
 2512,
 332,
 138,
 7,
 316,
 769,
 7,
 645,
 4,
 9,
 17,
 149,
 3,
 12,
 691,
 1178,
 57,
 691,
 723,
 138,
 13,
 3,
 206,
 6,
 88,
 8,
 444,
 281,
 206,
 6,
 88,
 8,
 527,
 138,
 7,
 149,
 3,
 12,
 1367,
 20,
 23,
 2,
 14,
 57,
 3,
 12,
 182,
 20,
 23,
 2,
 14,
 13,
 138,
 19,
 13,
 1368,
 5,
 102,
 52,
 428,
 1179,
 1984,
 690,
 10,
 358,
 16,
 276,
 138,
 178,
 7,
 42,
 6,
 825,
 1369,
 2,
 48,
 51,
 59,
 325,
 9,
 7,
 174,
 9,
 17,
 11,
 610,
 472,
 138,
 109,
 108,
 1064,
 7,
 42,
 2,
 51,
 255,
 138,
 40,
 7,
 23,
 2,
 66,
 9,
 46,
 191,
 23,
 2,
 68,
 133,
 3,
 770,
 58,
 126,
 9,
 17,
 6,
 1985,
 179,
 18,
 1,
 77,
 216,
 7,
 2,
 96,
 3,
 473,
 59,
 2,
 68,
 133,
 3,
 770,
 9,
 58,
 549,
 33,
 12,
 15,
 225,
 30,
 135,
 508,
 42,
 9,
 771,
 18,
 52,
 156,
 90,
 136,
 90,
 81,
 1,
 282,
 10,
 277,
 26,
 2,
 152,
 128,
 30,
 68,
 15,
 166,
 162,
 225,
 49,
 16,
 99,
 81,
 8,
 50,
 401,
 156,
 2514,
 66,
 1,
 162,
 225,
 11,
 1,
 62,
 35,
 20,
 1180,
 153,
 30,
 135,
 136,
 4,
 81,
 89,
 4,
 772,
 5,
 266,
 3,
 114,
 9,
 120,
 8,
 50,
 474,
 412,
 107,
 25,
 8,
 50,
 14,
 133,
 3,
 402,
 15,
 92,
 18,
 2,
 22,
 16,
 134,
 58,
 54,
 24,
 2,
 134,
 58,
 2,
 135,
 48,
 117,
 15,
 2515,
 2,
 135,
 48,
 117,
 10,
 333,
 32,
 219,
 2,
 249,
 4,
 10,
 429,
 20,
 128,
 52,
 54,
 2,
 646,
 185,
 189,
 16,
 267,
 2,
 68,
 1065,
 646,
 47,
 128,
 180,
 268,
 345,
 45,
 4,
 73,
 73,
 73,
 130,
 11,
 100,
 54,
 24,
 2,
 49,
 16,
 86,
 32,
 33,
 2516,
 44,
 180,
 15,
 299,
 413,
 180,
 15,
 1370,
 58,
 4,
 120,
 1592,
 180,
 773,
 54,
 40,
 17,
 6,
 197,
 93,
 4,
 38,
 17,
 44,
 107,
 3,
 283,
 70,
 138,
 346,
 6,
 157,
 647,
 8,
 888,
 3,
 317,
 58,
 3,
 74,
 724,
 18,
 52,
 35,
 107,
 3,
 317,
 58,
 3,
 74,
 225,
 138,
 2,
 22,
 16,
 889,
 9,
 3,
 6,
 890,
 403,
 256,
 2,
 49,
 16,
 224,
 9,
 100,
 138,
 141,
 13,
 12,
 79,
 183,
 79,
 263,
 37,
 79,
 55,
 69,
 182,
 177,
 69,
 141,
 27,
 164,
 18,
 24,
 69,
 228,
 2,
 148,
 23,
 169,
 581,
 69,
 17,
 13,
 2517,
 430,
 16,
 414,
 4,
 1,
 204,
 8,
 2,
 141,
 48,
 12,
 326,
 260,
 18,
 24,
 69,
 22,
 66,
 2,
 300,
 961,
 2,
 3,
 65,
 962,
 4,
 963,
 3,
 131,
 194,
 4,
 367,
 378,
 345,
 964,
 79,
 4,
 134,
 79,
 1,
 120,
 2,
 22,
 69,
 141,
 13,
 12,
 287,
 70,
 2,
 91,
 415,
 8,
 1,
 109,
 18,
 69,
 33,
 134,
 2,
 6,
 216,
 8,
 79,
 10,
 69,
 272,
 2,
 22,
 2518,
 92,
 44,
 49,
 16,
 278,
 79,
 49,
 16,
 165,
 79,
 49,
 16,
 1986,
 4,
 49,
 16,
 458,
 53,
 57,
 69,
 22,
 134,
 283,
 29,
 69,
 219,
 2,
 198,
 99,
 79,
 51,
 29,
 69,
 219,
 2,
 431,
 4,
 582,
 79,
 29,
 69,
 17,
 13,
 38,
 138,
 42,
 826,
 9,
 1593,
 58,
 1,
 774,
 1987,
 611,
 7,
 6,
 612,
 1988,
 11,
 235,
 138,
 141,
 13,
 19,
 334,
 139,
 5,
 2519,
 3,
 81,
 18,
 5,
 65,
 5,
 19,
 1989,
 58,
 139,
 5,
 775,
 3,
 12,
 138,
 827,
 8,
 27,
 7,
 13,
 266,
 9,
 17,
 776,
 1,
 827,
 8,
 489,
 7,
 13,
 1990,
 9,
 17,
 776,
 1,
 827,
 8,
 583,
 7,
 13,
 2520,
 9,
 17,
 776,
 4,
 1,
 827,
 8,
 40,
 7,
 13,
 199,
 9,
 17,
 776,
 138,
 7,
 13,
 6,
 891,
 8,
 27,
 18,
 6,
 891,
 8,
 445,
 10,
 219,
 777,
 2521,
 138,
 225,
 77,
 118,
 4,
 6,
 2523,
 892,
 56,
 7,
 1,
 1594,
 40,
 138,
 7,
 23,
 335,
 3,
 78,
 236,
 21,
 14,
 367,
 103,
 1068,
 138,
 27,
 2,
 108,
 347,
 59,
 37,
 29,
 37,
 72,
 139,
 5,
 27,
 2,
 550,
 108,
 828,
 37,
 829,
 5,
 27,
 2,
 11,
 56,
 80,
 54,
 5,
 36,
 13,
 51,
 154,
 103,
 80,
 8,
 404,
 18,
 56,
 11,
 122,
 38,
 7,
 46,
 5,
 37,
 2,
 44,
 1371,
 10,
 15,
 308,
 250,
 28,
 725,
 7,
 28,
 308,
 44,
 1371,
 10,
 29,
 5,
 229,
 648,
 15,
 220,
 405,
 138,
 91,
 649,
 2,
 14,
 778,
 2,
 243,
 1992,
 1372,
 8,
 205,
 138,
 2,
 726,
 43,
 2,
 19,
 46,
 67,
 3,
 27,
 50,
 138,
 32,
 584,
 965,
 11,
 1595,
 22,
 66,
 2,
 6,
 1596,
 121,
 401,
 65,
 10,
 965,
 11,
 6,
 1993,
 22,
 66,
 2,
 6,
 830,
 138,
 7,
 11,
 1,
 650,
 8,
 1,
 1597,
 4,
 9,
 141,
 12,
 612,
 72,
 67,
 3,
 67,
 3,
 134,
 6,
 332,
 37,
 1994,
 1597,
 6,
 475,
 650,
 138,
 2,
 14,
 2,
 10,
 7,
 1995,
 57,
 166,
 38,
 7,
 46,
 39,
 385,
 32,
 7,
 2525,
 57,
 2,
 138,
 2,
 60,
 15,
 318,
 3,
 12,
 585,
 124,
 50,
 651,
 613,
 24,
 2,
 60,
 50,
 3,
 12,
 53,
 585,
 124,
 50,
 53,
 651,
 613,
 138,
 7,
 386,
 3,
 82,
 108,
 1598,
 47,
 83,
 476,
 2,
 82,
 44,
 2526,
 10,
 2,
 257,
 35,
 153,
 13,
 19,
 432,
 47,
 25,
 11,
 122,
 831,
 2,
 646,
 64,
 1996,
 138,
 33,
 96,
 2,
 72,
 6,
 3,
 1599,
 490,
 33,
 96,
 2,
 1373,
 138,
 77,
 93,
 70,
 309,
 29,
 9,
 1181,
 2,
 2,
 132,
 46,
 210,
 138,
 53,
 10,
 2,
 124,
 1,
 53,
 63,
 2,
 33,
 51,
 1,
 53,
 10,
 2,
 211,
 1,
 53,
 586,
 2,
 135,
 81,
 138,
 477,
 9,
 7,
 966,
 217,
 15,
 299,
 377,
 18,
 160,
 45,
 269,
 127,
 10,
 267,
 10,
 9,
 7,
 13,
 214,
 138,
 179,
 7,
 238,
 7,
 133,
 3,
 278,
 2,
 2,
 52,
 212,
 3,
 117,
 1,
 282,
 336,
 416,
 20,
 138,
 25,
 8,
 78,
 ...]

Let's illustrate with a small example how `X` and `y` are formed. Imagine a simple tokenized sentence:

`simple_sequence = [1, 2, 3, 4]` (e.g., 'the quick brown fox')

For this sequence, `X` and `y` would be populated as follows:

In [23]:
simple_sequence = [1, 2, 3, 4] # Example: ['the', 'quick', 'brown', 'fox']

simple_X = []
simple_y = []

for i in range(1, len(simple_sequence)):
    input_seq = simple_sequence[:i]
    output_seq = simple_sequence[i]
    simple_X.append(input_seq)
    simple_y.append(output_seq)

print(f"Example X: {simple_X}")
print(f"Example y: {simple_y}")

Example X: [[1], [1, 2], [1, 2, 3]]
Example y: [2, 3, 4]

In [24]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_len=10
X=pad_sequences(X,maxlen=max_len)
X

array([[   0,    0,    0, ...,    0,    0,  722],
       [   0,    0,    0, ...,    0,  722,   62],
       [   0,    0,    0, ...,  722,   62,   35],
       ...,
       [ 499,    9,    7, ...,   10,   21, 1148],
       [   9,    7,   54, ...,   21, 1148,    3],
       [   7,   54,   21, ..., 1148,    3,  176]], dtype=int32)

In [25]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [26]:
print(X[20])

[ 74 287   9 151  12 824 108 768  74 287]

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM,Dense

In [28]:
embedding_dim=50
rnn_units=128

In [29]:
embedding_dim=50
rnn_units=128
rnn_model = Sequential()
rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim))
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size,activation="softmax"))
rnn_model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [30]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
embedding_dim=50
rnn_units=128
lstm_model=Sequential()
lstm_model.add(Embedding(input_dim=vocab_size,output_dim=embedding_dim))
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation="softmax"))

In [32]:
lstm_model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

In [33]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
epochs=10
batch_size=128

In [35]:
history_rnn = rnn_model.fit(
    X, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 49s 75ms/step - accuracy: 0.0406 - loss: 6.6404 - val_accuracy: 0.0555 - val_loss: 6.4682
Epoch 2/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 45s 72ms/step - accuracy: 0.0784 - loss: 5.9975 - val_accuracy: 0.0911 - val_loss: 6.1718
Epoch 3/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 46s 74ms/step - accuracy: 0.1048 - loss: 5.6236 - val_accuracy: 0.1054 - val_loss: 6.0994
Epoch 4/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 88s 84ms/step - accuracy: 0.1228 - loss: 5.3298 - val_accuracy: 0.1132 - val_loss: 6.0637
Epoch 5/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 76s 74ms/step - accuracy: 0.1379 - loss: 5.0700 - val_accuracy: 0.1159 - val_loss: 6.1172
Epoch 6/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 48s 77ms/step - accuracy: 0.1519 - loss: 4.8370 - val_accuracy: 0.1154 - val_loss: 6.1548
Epoch 7/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 44s 71ms/step - accuracy: 0.1661 - loss: 4.6194 - val_accuracy: 0.1183 - val_loss: 6.2383
Epoch 8/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 83s 73ms/step - accuracy: 0.1839 - loss: 4.4158 - val_accuracy: 0.1136 - val_loss: 6.2972
Epoch 9/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 44s 71ms/step - accuracy: 0.2055 - loss: 4.2239 - val_accuracy: 0.1131 - val_loss: 6.3863
Epoch 10/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 46s 73ms/step - accuracy: 0.2278 - loss: 4.0434 - val_accuracy: 0.1153 - val_loss: 6.4789

In [36]:
history_lstm = lstm_model.fit(
    X, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 58s 90ms/step - accuracy: 0.0396 - loss: 6.6648 - val_accuracy: 0.0437 - val_loss: 6.5279
Epoch 2/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 86s 96ms/step - accuracy: 0.0637 - loss: 6.1581 - val_accuracy: 0.0741 - val_loss: 6.3296
Epoch 3/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 56s 90ms/step - accuracy: 0.0880 - loss: 5.8885 - val_accuracy: 0.0912 - val_loss: 6.2406
Epoch 4/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 82s 89ms/step - accuracy: 0.1054 - loss: 5.6577 - val_accuracy: 0.1007 - val_loss: 6.1639
Epoch 5/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 84s 92ms/step - accuracy: 0.1157 - loss: 5.4526 - val_accuracy: 0.1098 - val_loss: 6.1465
Epoch 6/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 80s 89ms/step - accuracy: 0.1272 - loss: 5.2718 - val_accuracy: 0.1136 - val_loss: 6.1450
Epoch 7/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 55s 89ms/step - accuracy: 0.1375 - loss: 5.1095 - val_accuracy: 0.1180 - val_loss: 6.1669
Epoch 8/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 82s 88ms/step - accuracy: 0.1471 - loss: 4.9592 - val_accuracy: 0.1211 - val_loss: 6.1991
Epoch 9/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 85s 92ms/step - accuracy: 0.1554 - loss: 4.8162 - val_accuracy: 0.1234 - val_loss: 6.2266
Epoch 10/10
623/623 ━━━━━━━━━━━━━━━━━━━━ 56s 90ms/step - accuracy: 0.1651 - loss: 4.6772 - val_accuracy: 0.1220 - val_loss: 6.2803

In [37]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [38]:
word_index=tokenizer.word_index
index_to_word={}
for word,index in word_index.items():
  index_to_word[index]=word

In [39]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [44]:
def predictor(model,tokenizer,text,max_len):
  text=text.lower()
  seq=tokenizer.texts_to_sequences([text])[0]
  seq=pad_sequences([seq],maxlen=max_len,padding="pre")
  pred=model.predict(seq)
  pred=model.predict(seq,verbose=0)
  pred_index=np.argmax(pred)
  return index_to_word[pred_index]

In [47]:
seed_text="country"
next_word=predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
is

In [48]:
print(next_word)

is

In [50]:
def geenrate_text(model,tokenizer,seed_text,n_words,max_len):
  text=[]
  for _ in range(n_words):
    next_word=predictor(model,tokenizer,seed_text,max_len)
    if next_word=="":
      break
    seed_text+=" "+next_word
  return seed_text

In [52]:
seed="are you a"
generate_text=geenrate_text(lstm_model,tokenizer,seed,10,max_len)
print(generate_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
are you a man s a man who s a man who reads